### ISSUE TITLE
Fetched in submodule path 'HopperSDK', but it did not contain

### ISSUE THREAD

**Issue by AsTryE** [0xc010d/DYLDSharedCache.hopperLoader#1]
Mac-mini-2hao:t tangxianhai$ git clone https://github.com/0xc010d/DYLDSharedCache.hopperLoader.git DYLDSharedCache
Cloning into 'DYLDSharedCache'...
remote: Counting objects: 15, done.
remote: Total 15 (delta 0), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (15/15), done.
Mac-mini-2hao:t tangxianhai$ cd DYLDSharedCache
Mac-mini-2hao:DYLDSharedCache tangxianhai$ git submodule init && git submodule update
Submodule 'HopperSDK' (https://github.com/0xc010d/HopperSDK.git) registered for path 'HopperSDK'
Submodule 'dyld' (https://github.com/opensource-apple/dyld.git) registered for path 'dyld'
Cloning into '/Users/tangxianhai/Desktop/t/DYLDSharedCache/HopperSDK'...
Cloning into '/Users/tangxianhai/Desktop/t/DYLDSharedCache/dyld'...
error: no such remote ref c34fce19f75073a2c9d2e7367c74bbb2ef2e929e
Fetched in submodule path 'HopperSDK', but it did not contain c34fce19f75073a2c9d2e7367c74bbb2ef2e929e. Direct fetching of that commit failed.

**Comment by 0xc010d** [comment]
Fixed, thanks for reporting.

**Comment by AsTryE** [comment]
method name is redacted,how to solve it
